import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import PromoBanner from "@/components/banners/promo-banner";
import { SiteHeader } from "@/components/navigation/site-header";
import { AppProviders } from "@/providers/app-providers";
import { AuthProvider } from "@/providers/auth-provider";
import { QueryProvider } from "@/providers/query-provider";

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} antialiased`}>
        <AuthProvider>
          <AppProviders>
            <QueryProvider>
              <PromoBanner />
              {/* Make the WHOLE header sticky */}
              <header className="sticky top-0 z-40 bg-background/80 backdrop-blur border-b">
                <SiteHeader />
              </header>

              {/* With sticky you usually don't need extra padding */}
              <main>{children}</main>
            </QueryProvider>
          </AppProviders>
        </AuthProvider>
      </body>
    </html>
  );
}
